image: python:latest
pages:
  stage: deploy
  only:
    - master 
    - main
  script:
    - pip install mkdocs-material mkdocs-add-number-plugin
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

