site_name: 智能系统设计与实践
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 欢迎: index.md
  - 课程概述: INTRO.md
  - 实验介绍:
    - 系统架构: ARCH.md
    - 镜像平台与自动评测系统: REGISTRY.md
    - 作业:
      - HW1: hw1.md
    - 比赛项目:
      - RMUS 2022: CONTEST.md
      - 2022秋季课程: CONTEST-2022FALL.md
  - 操作指南:
    - 准备环境:
      - Windows系统-虚拟机: how-to/vm.md
      - Windows系统-WSL: how-to/wsl.md
      - Linux系统: how-to/linux-docker.md
    - 获取Docker镜像: how-to/prepare-images.md
    - 启动仿真环境: how-to/start-sim-env.md
    - 启动仿真EP: how-to/start-sim-ep.md
  - 参数与接口:
    - Robomaster EP: EP.md
  - FAQ: FAQ.md
  - 更新说明: UPDATES.md

plugins:
  - add-number:
      order: 2
      excludes: 
        - UPDATES.md
        - index.md
